[global]
  sendAnonymousUsage = false

[log]
  level = "DEBUG"
  format = "common"

[entryPoints]
  [entryPoints.insecure]
    address = ":80"
  [entryPoints.secure]
    address = ":443" 

[providers.docker]

[api]
  dashboard = true
  debug = false
  insecure = true

	